custom_fields_sample_app/README
request_list_with_add_ticket_sample_app/README

- added some basic READMEs to the individual repos.
@brendan-fahy @schlan @ndobri @mathewcropper 
@KevinLambe 
* None

Added basic READMEs to each sample project

---

chat_api_sample/README.md

Standardising on Apache Software Licence 2.0 for sample apps.

Standardise on ASL 2.0 for licencing

---

build.gradle

* Update to Chat SDK 1.3.7.1
@zendesk/adventure-android @zendesk/two-brothers-android @baz8080

Update to Chat SDK 1.3.7.1

---

ISSUES_TEMPLATE.md

* Added an issues template to help guide people creating new issues in
this repo
@zendesk/adventure-android @zendesk/two-brothers-android @zendesk/ogham

Issues Template

---

chat_api_sample/README.md

* Update chat_api_sample Readme.md

[BW] Update chat_api_sample Readme.md

---

support_urbanairship_sample/README.md

* Update README.md in support_urban_airship

[BW] Update README.md in support_urban_airship

---

answerbot_sample/src/main/res/values/styles.xml
build.gradle
support_override_styles/src/main/res/values/styles.xml
support_request_updates_sample/src/main/java/com/zendesk/support_request_updates_sample/Global.java
support_request_updates_sample/src/main/res/values/styles.xml
support_sample/src/main/java/com/zendesk/sample/Global.java
support_sample/src/main/res/values/styles.xml
support_upload_attachment_sample/src/main/java/com/zendesk/sample/uploadattachment/Global.java
support_urbanairship_sample/src/main/java/com/zendesk/example/ua/Global.java
support_urbanairship_sample/src/main/java/com/zendesk/example/ua/IntentReceiver.java
support_urbanairship_sample/src/main/res/values/zd.xml

* Update to Support SDK 2.3.0
* Update Gradle and Kotlin
* Fix a few of the `Global` classes where the Zendesk config constants that would cause an error on screen weren't actually being used to initialise the SDK. 
* Update a few of the samples to use `MaterialComponents` instead of `AppCompat`. 

Update to Support SDK 2.3.0 + a few tweaks

---

build.gradle
chat_api_sample/build.gradle
chat_api_sample/src/main/res/layout/activity_chat.xml
chat_api_sample/src/main/res/layout/activity_main.xml
chat_api_sample/src/main/res/layout/chat_log_agent_holder.xml
chat_api_sample/src/main/res/layout/chat_log_visitor_holder.xml
support_urbanairship_sample/build.gradle
support_urbanairship_sample/src/main/java/com/zendesk/example/ua/MainActivity.java

* Upgrade to Support v2.3.1 
* Update other dependencies

Upgrade to Support 2.3.1

---

build.gradle

Update Chat SDK to v1.4.4

---

build.gradle

* Bump Zendesk Chat SDK to the latest version

Update Chat SDK to v1.4.5

---

build.gradle
connect_sample/src/main/java/com/zendesk/sample/connect/Global.java
connect_sample/src/main/res/values/strings.xml

* Update Connect demo to v2.1.0
* Creating default and silent notification channels
* Overriding string resources

Update Connect demo to v2.1.0

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Update SDK Dependencies
* Support 3.0.0
* Answer Bot 1.0.0
* Kotlin and Android Build Tools version

[SGA-921] Update SDK Dependencies

---

build.gradle

* Update dependencies for Support and Answer Bot

[SGA-1084] Update dependencies for Support and Answer Bot

---

build.gradle

* Update Chat SDK to v1.4.7
@zendesk/adventure-android @zendesk/two-brothers-android @zendesk/atom-android @DanSessions

[MCU-599] Update Chat SDK to v1.4.7

---

answerbot_sample/proguard-rules.pro

* Add Proguard rules for building Answer Bot sample app as advised in our docs https://developer.zendesk.com/embeddables/docs/answer-bot-sdk-android/use_proguard

Update Answer Bot Proguard Rules

---

build.gradle

* Upgrade Support SDK to version 3.0.2

[SGA-2127] Upgrade Support SDK to version 3.0.2

---

build.gradle

* Upgrade to Support SDK 3.0.3

[SGA-2265] Upgrade to Support SDK 3.0.3

---

build.gradle

[MCU-1104] Update Chat SDK to v1.4.8

---

messaging_sample/src/main/AndroidManifest.xml
messaging_sample/src/main/java/com/zendesk/messaging_sample/Global.java
messaging_sample/src/main/res/values/styles.xml

* Set the Application subclass in the AndroidManifest
* Use a MaterialComponents theme
* Initialise AnswerBot. 

Fix broken Messaging sample app

---

build.gradle

[MCU-1717] Update Chat SDK to v1.4.9

---

.github/PULL_REQUEST_TEMPLATE.md

[BW] Update PR template

---

build.gradle

[MCU-3060] Update sample apps to chatv3.1.0

---

build.gradle

[MFD-3775] Update to latest versions

---

answerbot_sample/src/main/java/com/zendesk/answerbot_sample/Global.java

updating ab app

---

talk_sample/README.md

* Adding a README.md file. 
* @zendesk/banshee-android

[BW] Adding a README.md file to the Talk demo app.
